### ISSUE TITLE
Crash upon entering new level

### ISSUE THREAD

**Issue by Lexicon0523** [abevol/MultiReward#1]
When entering Erebus, the game immediately crashes with a bug report. If trying to uninstall/reinstall the mod at points, it will crash again whenever entering a new level. 

![image](https://github.com/abevol/MultiReward/assets/170374388/e9207db0-1674-48c7-9a45-9d140e87e2f3)

Mods installed:
![image](https://github.com/abevol/MultiReward/assets/170374388/e7130ebf-d47d-4e29-a4e8-0d56dc9383ff)

Config has been unedited.

**Comment by abevol** [comment]
You should provide some error logs, but based on feedback from others and my own testing, there currently seems to be an issue with the mod being incompatible with Chalk-2.0.2. 
I'm looking into this issue, and it appears to be a problem with Chalk-2.0.2. 
I've raised an issue and am waiting for a response from the author.

**Comment by abevol** [comment]
I have updated the mod to version [1.0.2](https://github.com/abevol/MultiReward/releases/tag/1.0.2), and the compatibility issue with Chalk-2.0.2 has been fixed.
If the new version has resolved your issue, please close it.

**Comment by Lexicon0523** [comment]
Thank you!
