### ISSUE TITLE
Implementation of In-Game UI

### ISSUE THREAD

**Issue by Siuhnexus** [abevol/MultiReward#4]
As a next step, I would like to look into implementing an In-Game UI for the mod, which could be opened with a hotkey. This menu could look similar to the vow screen so you can increase or decrease each config value.
A little extra idea I had would be to spawn Echo in the Crossroads and make the menu accessible via interaction with her.
Do you have any thoughts on this?

**Comment by abevol** [comment]
If it's just for this mod to implement such a complex feature, I think it might not be very cost-effective. The configuration tasks could be left to a configuration file manager. Alternatively, consider creating a universal in-game mod configuration manager, akin to ModMenu in MC. That would be a worthwhile endeavor.

如果只是为了这个模组而制作这样一个复杂的功能，我认为不太划算，配置的事情就交给配置文件管理器去做就好了，或者可以考虑去做一个通用的游戏内的模组配置管理器，就像MC里的ModMenu一样，这是一件值得去做的事情。

**Comment by Siuhnexus** [comment]
Alright thank you. I will think about it.
